name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/10 * * * *'  # 10분마다 실행 (UTC 기준)
  workflow_dispatch:        # 수동 실행도 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/Team-07-Project/Team-07-Project.git
          git fetch upstream

      - name: Set Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "🔁 Sync from upstream"

      - name: Remove upstream workflows
        run: |
          rm -rf .github/workflows
          git add -u .github/workflows || true
          git commit -m "chore: remove upstream workflows" || echo "No changes to commit"

      - name: Push to origin
        run: git push origin main
